version: "3.5"
services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ostock_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      - backend
  eurekaserver:
    image: ostock/eurekaserver:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
#      EUREKA_INSTANCE_HOSTNAME: eurekaserver
#      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
#      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    networks:
      - backend
    depends_on:
      - configserver
  gatewayserver:
    image: ostock/gatewayserver:0.0.1-SNAPSHOT
    ports:
      - "8072:8072"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
#      PROFILE: "default"
#      SERVER_PORT: "8072"
#      CONFIGSERVER_PORT: "8071"
#      CONFIGSERVER_URI: "http://configserver:8071"
#      EUREKASERVER_URI: "http://eurekaserver:8070/eureka"
#      EUREKASERVER_PORT: "8070"
    networks:
      backend:
        aliases:
          - "gateway"
  licensing-service:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: licensing-service
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ostock_dev
      SPRING_DATASOURCE_USER: postgres
      SPRING_DATASOURCE_PASSWORD: '{cipher}0927d4500872b0de2261621c34b0f16e56a3dc145733528ba895be0971949263'
      ENCRYPT_KEY: "IMSYMMETRIC"
    networks:
      - backend
    depends_on:
      - configserver
      - database
  organization-service:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: organization-service
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ostock_dev
      SPRING_DATASOURCE_USER: postgres
      SPRING_DATASOURCE_PASSWORD: '{cipher}0927d4500872b0de2261621c34b0f16e56a3dc145733528ba895be0971949263'
      ENCRYPT_KEY: "IMSYMMETRIC"
    networks:
      - backend
    depends_on:
      - configserver
      - database
networks:
  backend:
    driver: bridge
