apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: configserver
  name: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: configserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: configserver
    spec:
      containers:
        - env:
            - name: ENCRYPT_KEY
              value: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo
          image: 665971472586.dkr.ecr.us-east-1.amazonaws.com/ostock/configserver:chapter12
          name: configserver
          ports:
            - containerPort: 8071
          resources: {}
      restartPolicy: Always
status: {}
