apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: licensing-service
  name: licensing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: licensing-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: licensing-service
    spec:
      containers:
        - env:
            - name: ENCRYPT_KEY
              value: IMSYMMETRIC
            - name: SPRING_APPLICATION_NAME
              value: licensing-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://configserver:8071
            - name: SPRING_DATASOURCE_PASSWORD
              value: '{cipher}0927d4500872b0de2261621c34b0f16e56a3dc145733528ba895be0971949263'
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://database:5432/ostock_dev
            - name: SPRING_DATASOURCE_USER
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: dev, aws-dev
          image: 665971472586.dkr.ecr.us-east-1.amazonaws.com/ostock/licensing-service:chapter12
          name: licensing-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
