apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-service.yaml
spec:
  type: ExternalName
  externalName: ostock-aws.ccweifsogqgn.us-east-1.rds.amazonaws.com
  selector:
    app: postgres-service
status:
  loadBalancer: {}
