apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server.yaml
spec:
  type: ExternalName
  externalName: ostock-redis.wfogwe.ng.0001.use1.cache.amazonaws.com
  selector:
    app: redis-server
status:
  loadBalancer: {}
