apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: gatewayserver
  name: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gatewayserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: gatewayserver
    spec:
      containers:
        - env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://configserver:8071
            - name: SPRING_PROFILES_ACTIVE
              value: aws-dev
          image: 665971472586.dkr.ecr.us-east-1.amazonaws.com/ostock/gatewayserver:chapter12-1
          name: gatewayserver
          ports:
            - containerPort: 8072
          resources: {}
      restartPolicy: Always
status: {}
