apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: licensing-service
  name: licensing-service
spec:
  ports:
    - name: "8180"
      port: 8180
      targetPort: 8080
  selector:
    io.kompose.service: licensing-service
status:
  loadBalancer: {}
