apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: organization-service
  name: organization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: organization-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: organization-service
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_NAME
              value: organization-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://configserver:8071
            - name: SPRING_PROFILES_ACTIVE
              value: dev,aws-dev
          image: 665971472586.dkr.ecr.us-east-1.amazonaws.com/ostock/organization-service:chapter12-1
          name: organization-service
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
