apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-service
  name: postgres-service
spec:
  type: ExternalName
  externalName: ostockdbinstance.ccweifsogqgn.us-east-1.rds.amazonaws.com
  selector:
    app: postgres-service
status:
  loadBalancer: {}
