version: "3.5"
services:
  authenticationservice:
    image: ostock/authentication-service:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: authentication-service
    networks:
      backend:
  barservice:
    image: ostock/bar-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: bar-service
    networks:
      backend:
  fooservice:
    image: ostock/foo-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: foo-service
    networks:
      backend:
networks:
  backend:
    driver: bridge
